import random

# Create a larger list of unique sentences
unique_sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "Artificial Intelligence is transforming the world.",
    "Python is a versatile programming language.",
    "Data Science is an exciting field to explore.",
    "Machine learning algorithms can learn from data.",
    "Natural language processing enables computers to understand human language.",
    "Robotics combines engineering and computer science.",
    "Quantum computing has the potential to revolutionize technology.",
    "The future of transportation includes electric vehicles.",
    "Sustainable energy solutions are essential for the planet.",
    "Cybersecurity is crucial in the digital age.",
    "Big data analytics provides insights from vast data sets.",
    "Blockchain technology ensures secure transactions.",
    "Cloud computing offers scalable resources on demand.",
    "Augmented reality enhances our interaction with the world.",
    "Virtual reality provides immersive experiences.",
    "The Internet of Things connects everyday devices.",
    "5G technology will enable faster wireless communication.",
    "Ethical considerations are important in AI development.",
    "Open-source software promotes collaboration and innovation.",
    "User experience design focuses on optimizing usability.",
    "Graphic design is an art form that communicates visually.",
    "Web development combines creativity and technical skills.",
    "Digital marketing strategies leverage online platforms.",
    "Social media influences modern communication.",
    "Content creation drives engagement and brand awareness.",
    "E-commerce has transformed the retail landscape.",
    "Mobile applications enhance user convenience.",
    "Video production has become accessible to everyone.",
    "Photography captures moments in time.",
    "Writing is a powerful form of expression.",
    "Journalism plays a vital role in a democratic society.",
    "Public speaking skills are valuable in many professions.",
    "Negotiation skills can lead to better outcomes.",
    "Project management ensures successful project completion.",
    "Time management is key to productivity.",
    "Team collaboration fosters innovation and creativity.",
    "Leadership involves guiding and inspiring others.",
    "Emotional intelligence enhances interpersonal relationships.",
    "Critical thinking is essential for problem-solving.",
    "Analytical skills enable data-driven decision-making.",
    "Coding challenges improve programming proficiency.",
    "Software testing ensures product quality.",
    "Networking can open up new career opportunities.",
    "Research skills are vital for academic success.",
    "Presentation skills enhance communication effectiveness.",
    "Strategic planning sets a clear direction.",
    "Adaptability is crucial in a changing world.",
    "Conflict resolution skills promote harmony.",
    "Mentorship provides guidance and support.",
    "Cultural awareness fosters inclusivity.",
    "Diversity enriches the workplace environment.",
    "Inclusion encourages participation from all individuals.",
    "Self-care is important for mental health.",
    "Mindfulness practices reduce stress and anxiety.",
    "Physical fitness contributes to overall well-being.",
    "Healthy eating habits improve energy levels.",
    "Sleep hygiene is essential for productivity.",
    "Hobbies enhance personal fulfillment.",
    "Volunteering benefits both individuals and communities.",
    "Traveling broadens one’s perspective.",
    "Learning a new language opens doors to new cultures.",
    "Music has the power to evoke emotions.",
    "Art inspires creativity and innovation.",
    "Science explores the mysteries of the universe.",
    "History teaches us valuable lessons.",
    "Philosophy encourages deep thinking.",
    "Mathematics is the language of the universe.",
    "Geography shapes our understanding of the world.",
    "Literature reflects the human experience.",
    "Theater brings stories to life.",
    "Film is a powerful storytelling medium.",
    "Dance is a form of artistic expression.",
    "Crafting nurtures creativity and skill.",
    "Gardening connects us with nature.",
    "Cooking is a blend of art and science.",
    "Fashion reflects personal style and culture.",
    "Interior design transforms spaces.",
    "Home improvement projects enhance living environments.",
    "DIY projects foster creativity and resourcefulness.",
    "Pet ownership provides companionship and joy.",
    "Sports promote teamwork and healthy competition.",
    "Outdoor activities encourage an active lifestyle.",
    "Adventure can lead to personal growth.",
    "Nature has a calming effect on the mind.",
    "Wildlife conservation is vital for biodiversity.",
    "Environmental protection ensures a sustainable future.",
    "Climate change is a pressing global issue.",
    "Public health initiatives improve community well-being.",
    "Education empowers individuals and communities.",
    "Skill development enhances employability.",
    "Entrepreneurship drives economic growth.",
    "Innovation leads to new solutions.",
    "Success is a journey, not a destination.",
    "Personal development is a lifelong process.",
    "Goal setting helps to achieve aspirations.",
    "Positive thinking fosters resilience.",
    "Kindness can change the world.",
    "The journey of a thousand miles begins with one step.",
    "Every cloud has a silver lining.",
    "Actions speak louder than words.",
    "Brevity is the soul of wit.",
    "A picture is worth a thousand words.",
    "Beauty is in the eye of the beholder.",
    "The pen is mightier than the sword.",
    "Fortune favors the bold.",
    "Knowledge is power.",
    "A journey of a thousand miles begins with a single step.",
    "Good things come to those who wait.",
    "Time and tide wait for no man.",
    "Don't count your chickens before they hatch.",
    "You can't judge a book by its cover.",
    "What goes around comes around.",
    "Every rose has its thorn.",
    "Life is a journey, not a destination.",
    "Carpe diem - seize the day!",
    "When life gives you lemons, make lemonade.",
    "Hope for the best, but prepare for the worst.",
    "An ounce of prevention is worth a pound of cure.",
    "The best time to plant a tree was 20 years ago.",
    "You miss 100% of the shots you don't take.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
]

# Randomly sample 100 unique sentences
random_sentences = random.sample(unique_sentences, 100)

# Write to a text file
with open("sentences.txt", "w") as file:
    for sentence in random_sentences:
        file.write(sentence + "\n")

print("Sentences written to sentences.txt.")

